spring:
  application:
    name: kang-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kang_ai_code_mother
    username: root
    password: root
  # redis
  data:
    redis:
      database: 5
      host: localhost
      port: 6379
      password:
      ttl: 3600
  profiles:
    active: local
  # java Mail
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 2116077303@qq.com
    password: ngoncebyjpitejba
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          socketFactory.port: 465
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: net.pkk.kangaicodemother.controller
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192  # 请求的最大令牌数
      strict-json-schema: true  # 严格模式
      response-format: json_object # 响应格式
      log-requests: true # 请求日志
      log-responses: true # 响应日志
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192  # 请求的最大令牌数
      log-requests: true # 请求日志
      log-responses: true # 响应日志
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
